const {createClient}=supabase;
const db=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const benefits=[{p:200,t:'5% de descuento'},{p:400,t:'10% de descuento'},{p:600,t:'Envío gratis'},{p:800,t:'15% de descuento'},{p:1000,t:'Beneficio especial'}];
const $=s=>document.querySelector(s);
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function level(p){if(p>=1000)return'Platinum';if(p>=800)return'Gold';if(p>=600)return'Silver';if(p>=400)return'Bronze';return'Inicial'}
function renderBenefits(){$('#benefitGrid').innerHTML=benefits.map(b=>`<article class="benefit"><div class="points">${b.p} pts</div><h3>${b.t}</h3><p>Beneficio de fidelización NALYCO.</p></article>`).join('')}
async function currentClient(){const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data,error}=await db.from('clientes').select('*').eq('correo',user.email).maybeSingle();if(error)throw error;return data}
async function showAccount(){try{const c=await currentClient();if(!c){toast('No encontramos tu registro de cliente.');return}const {data:purchases,error}=await db.from('compras').select('*').eq('cliente_id',c.id).order('fecha_compra',{ascending:false});if(error)throw error;$('#cuenta').classList.remove('hidden');$('#accountName').textContent=c.nombre;$('#accountCode').textContent=`Código: NALYCO-${String(c.id).padStart(3,'0')}`;$('#accountPoints').textContent=c.puntos;$('#accountLevel').textContent=c.nivel||level(c.puntos);const next=benefits.find(b=>c.puntos<b.p)||benefits[benefits.length-1];$('#nextBenefit').textContent=next.t;const prev=benefits[benefits.indexOf(next)-1]?.p||0;$('#progressBar').style.width=Math.min(100,Math.max(0,(c.puntos-prev)/(next.p-prev)*100))+'%';$('#progressText').textContent=c.puntos>=1000?'¡Tienes el nivel máximo!':`Te faltan ${Math.max(0,next.p-c.puntos)} puntos para ${next.t}.`;$('#purchaseHistory').innerHTML=(purchases||[]).map(x=>`<div style="padding:12px 0;border-bottom:1px solid #eee"><b>${x.producto||'Compra'}</b> · ${x.fecha_compra||''} · $${Number(x.valor||0).toLocaleString('es-CO')} · ${x.cantidad||1} unidad(es)</div>`).join('')||'<p>No hay compras registradas.</p>';location.hash='cuenta'}catch(e){console.error(e);toast('No se pudo consultar la cuenta.')}}
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target),email=f.get('email').trim().toLowerCase();const {data,error}=await db.auth.signUp({email,password:prompt('Crea una contraseña para tu cuenta NALYCO (mínimo 6 caracteres):')});if(error)throw error;const {error:ie}=await db.from('clientes').insert({nombre:f.get('name').trim(),telefono:f.get('phone').trim(),correo:email,ciudad:f.get('city').trim(),puntos:0,nivel:'Inicial'});if(ie && !ie.message.includes('duplicate'))throw ie;toast('Cuenta creada. Revisa tu correo si Supabase solicita confirmación.');e.target.reset();setTimeout(showAccount,800)}catch(err){console.error(err);toast(err.message||'No se pudo crear la cuenta.')}});
$('#loginBtn').addEventListener('click',async()=>{const email=prompt('Correo registrado en NALYCO:');if(!email)return;const password=prompt('Contraseña de tu cuenta:');if(!password)return;const {error}=await db.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){toast('No se pudo iniciar sesión: '+error.message);return}await showAccount()});
$('#logoutBtn').addEventListener('click',async()=>{await db.auth.signOut();$('#cuenta').classList.add('hidden');location.hash='inicio'});
$('#adminBtn').addEventListener('click',()=>{toast('El panel administrativo requiere una cuenta de administrador en Supabase. La configuración del rol se hará antes de publicar.')});
renderBenefits();
(async()=>{const {data:{session}}=await db.auth.getSession();if(session)showAccount()})();
